require("klosiu.plugins-setup")
require("klosiu.core.colorscheme")
require("klosiu.core.options")
require("klosiu.core.keymaps")
require("klosiu.plugins.nvim-tree")
require("klosiu.plugins.lualine")
require("klosiu.plugins.nvim-cmp")
require("klosiu.plugins.telescope")
require("klosiu.plugins.autopairs")
require("klosiu.plugins.gitsigns")
require("klosiu.plugins.lsp")
require("klosiu.plugins.comment")
require("klosiu.plugins.treesitter")
require("klosiu.plugins.nvterm")

